# Generated by Django 3.2.8 on 2021-11-15 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_api', '0005_alter_appointment_date_of_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date_of_appointment',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='birthdate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.BooleanField(),
        ),
    ]
