# Generated by Django 3.2.8 on 2021-11-15 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_api', '0006_auto_20211115_1831'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.CharField(max_length=200, null=True)),
                ('appointment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic_api.appointment')),
                ('doctor_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clinic_api.doctor')),
                ('patient_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clinic_api.patient')),
            ],
        ),
    ]
