# Generated by Django 3.2.8 on 2021-11-20 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_api', '0008_alter_comment_doctor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='patient_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient', to='clinic_api.patient'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='doctor_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clinic_api.doctor'),
        ),
    ]
